### PR TITLE
fix(Script): Offhand visual / server crash

### LINKED ISSUE #3: [Crash]
The server crash when player switch  an enchanted off hand

### PR DESCRIPTION
**Pull request by ghost**
- fix loading offhand visual
- fix server crash when switching fake enchanted offhand

Closes #3 

Tested build on Ubuntu 16.04 / clang 7; tested successfully in-game

### CODE REVIEW

**Comment by milestorme** [comment]
Will test this today

**Comment by ghost** [comment]
Btw, do not mind the Travis run, it is missing the creation of table "custom_item_enchant_visuals". This will be fixed after PR #5 has been merged.

**Comment by milestorme** [comment]
im not getting a crash but item visual is not saving to the database on pr #4 AC>AzerothCore rev. 68a998c79e9c+ 2019-05-26 13:09:40 +0000 (master branch) (Unix, Release)

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by ghost** [comment]
@milestorme 
Are you sure you applied the PR correctly? I just tested once more and the data is correctly saved to the DB for both main and offhand items. After logout / login the visual effects are visible (tested it with two random swords).

**Comment by milestorme** [comment]
I followed the same pr method as on our wiki , and before the change it was saving for me but had the crash bug , I tryed updating the table to UTF8 too to see if it was that and still didn’t save anything to the table

**Comment by ghost** [comment]
Have you recompiled AC after applying this PR? Do you get any error messages? This PR did not even touch the "replace"-statement, so I don't understand why it does not work for you. The only thing I changed is this: While looping through each DB entry for the player the item GUID is compared to both your main and offhand and if they match the visual effect is applied.

**Comment by FrancescoBorzi** [comment]
> The DBErrors.log file contains startup errors:
2019-05-28 23:37:00 Script named 'npc_visualweapon' does not have a script name assigned in database.

**Comment by ghost** [comment]
@FrancescoBorzi 
Yes, I know, but this is only a Travis problem, because it tries to execute a DB check but cannot find the table as it is not yet available for db_assembler (see PR #5 ).

**Comment by milestorme** [comment]
I compiled the core fresh , No errors on compile no warnings , seems to work you can apply enchant and if you don’t log out your fine , if I check my characters database the table custom _item_enchant_visual is empty , I get no console errors either . I noticed the changes had nothing to do with the replace statement  I’m confused as to why it’s working for you and not for me can someone else test this please

**Comment by BarbzYHOOL** [comment]
Milestorme, are you on windows? do you have other modules?

**Comment by milestorme** [comment]
on Linux , heres the pr pull log , like I said this module works for me before the changes it just crash's randomly

mic_2@DESKTOP-RHOSPDS MINGW64 ~/Desktop/mod-weapon-visual (master)               $ git checkout -b pr-4                                                           Switched to a new branch 'pr-4'                                                                                                                                   mic_2@DESKTOP-RHOSPDS MINGW64 ~/Desktop/mod-weapon-visual (pr-4)                 $ git pull origin pull/4/head                                                    remote: Enumerating objects: 7, done.                                            remote: Counting objects: 100% (7/7), done.                                      remote: Compressing objects: 100% (2/2), done.                                   remote: Total 4 (delta 2), reused 4 (delta 2), pack-reused 0                     Unpacking objects: 100% (4/4), done.                                             From https://github.com/azerothcore/mod-weapon-visual                             * branch            refs/pull/4/head -> FETCH_HEAD                              Updating 93f6e8a..5a5a79f                                                        Fast-forward                                                                      src/Npc_VisualWeapon.cpp \| 18 ++++++++----------                                 1 file changed, 8 insertions(+), 10 deletions(-)                                                                                                                 mic_2@DESKTOP-RHOSPDS MINGW64 ~/Desktop/mod-weapon-visual (pr-4)
--

**Comment by ghost** [comment]
Ok, tried once more:
- clone AC
- clone module
- pull PR 4
- compile
- create new table "custom_item_enchant_visuals"
- create new entry for the NPC in "creature_template"
- spawn NPC in-game, use enchants for both weapons, both saved to the DB

Sorry, I have no clue what's wrong here.

**Comment by milestorme** [comment]
this step fixed it for me , i had the table there already in latin i converted it to utf8 but didnt work , deleted the table and create new table "custom_item_enchant_visuals" working on logout loggin and saving. Sorry for that that was annoiying

**Comment by milestorme** [comment]
its just an id10t user error on my behalf :)

**Comment by milestorme** [comment]
Confirm pr #4 working on , no off hand server crash and visuals are saving  AC>AzerothCore rev. 68a998c79e9c+ 2019-05-26 13:09:40 +0000 (master branch) (Unix, Release)

**Comment by ghost** [comment]
Great, thanks for clearing this up. 👍

**Comment by ghost** [comment]
Merged, as the Travis run was now also ok. Thanks for testing @milestorme !

**Comment by BarbzYHOOL** [comment]
thank you @Stoabrogga and @milestorme

**Pull request merged**
