### PR TITLE
Fix Build

### LINKED ISSUE #22: Errors while building
Hello together,

when I build the AC files with the module in VS 22 some errors occurs.

15>E:\WoWServerDev\Azerothcore\modules\mod-weapon-visual\src\Npc_VisualWeapon.cpp(119,27): error C2039: "PExecute" ist kein Member von "DatabaseWorkerPool<CharacterDatabaseConnection>".
15>E:\WoWServerDev\Azerothcore\src\server\database\Database\DatabaseEnv.h(37): message : Siehe Deklaration von "DatabaseWorkerPool<CharacterDatabaseConnection>"
15>E:\WoWServerDev\Azerothcore\modules\mod-weapon-visual\src\Npc_VisualWeapon.cpp(204,48): error C2039: "PQuery" ist kein Member von "DatabaseWorkerPool<CharacterDatabaseConnection>".
15>E:\WoWServerDev\Azerothcore\src\server\database\Database\DatabaseEnv.h(37): message : Siehe Deklaration von "DatabaseWorkerPool<CharacterDatabaseConnection>"
15>E:\WoWServerDev\Azerothcore\modules\mod-weapon-visual\src\Npc_VisualWeapon.cpp(213,42): error C2039: "GetUInt32" ist kein Member von "Field".
15>E:\WoWServerDev\Azerothcore\src\server\database\Database\Field.h(98): message : Siehe Deklaration von "Field"
15>E:\WoWServerDev\Azerothcore\modules\mod-weapon-visual\src\Npc_VisualWeapon.cpp(214,39): error C2039: "GetUInt32" ist kein Member von "Field".
15>E:\WoWServerDev\Azerothcore\src\server\database\Database\Field.h(98): message : Siehe Deklaration von "Field"

Thanks for any possible help

### PR DESCRIPTION
**Pull request by Shadowveil-WotLK**
Fixes #22  =)

### CODE REVIEW

**Comment by Helias** [comment]
thanks for your PR, update your branch with master to fix the pipeline please

**Comment by Shadowveil-WotLK** [comment]
> thanks for your PR, update your branch with master to fix the pipeline please

is updated now =)

**Comment by Helias** [comment]
the dry run step failed, I restarted the pipeline

**Comment by Shadowveil-WotLK** [comment]
hmmm...

I checked now with the mod the startup of worldserver... and it shows a behaviour which it has shown nearly 1 year ago as well...

It doesn't load beyond the "Loading C++ Scripts" at worldserver startup and crashes then with CharacterDatabaseConnection...

Will look if I can change the code there a bit so it does proceed with the startup... since sql sided everything is properly applied ^^
here the crashlog so u see what I mean:
https://drive.google.com/file/d/19faocwTaggSA40k23HGgLWuQZPp4lPWE/view?usp=share_link

**Comment by Shadowveil-WotLK** [comment]
changed now some parts at the character db queries again... tested after build success if worldserver starts up properly...

looks now all fine =)

and yeah... sorry in case I need a bit longer for stuff... started with learning all that c++ stuff not long ago =D

**Comment by Helias** [comment]
I started the build, unfortunately it requires an approve to start in the modules

**Comment by Helias** [comment]
image

**Comment by Shadowveil-WotLK** [comment]
hmmm... will check the original sql file of it... eventually there is an error inside since I using for it a totally different creature id due to already used on me... and due to that I prob wouldn't even have recognized that SQL error... will check it out after I have eaten ^^

**Comment by Shadowveil-WotLK** [comment]
should work out now in regular... changed the SQL file according to my serverside entry and there all works fine when pulling the SQL file manually to the database (like I am used to it from nearly all mods)
image

**Comment by Helias** [comment]
try to respect the same directory structure of this module https://github.com/azerothcore/mod-transmog/tree/master/data/sql
if you respect the same directory structure AC will load automatically during the build and the dry run the sql files, currently it does not load the sql files so the build fails

**Comment by Shadowveil-WotLK** [comment]
aha. i see i see =)
i will look at it. thx for the advice =)

**Comment by Helias** [comment]
it worked!

**Comment by Shadowveil-WotLK** [comment]
glad I could help with fixing the build =D

and thx again for the hint with the sql storage names ^.^

**Pull request merged**
