### PR TITLE
ObjectGuid: Part I.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by UltraNix** [comment]
Failed at DB import - unrelated to the PR.

**Comment by ghost** [comment]
Ready to be merged.

**Comment by FrancescoBorzi** [comment]
@UltraNix build fails

**Comment by ghost** [comment]
@FrancescoBorzi Not my fault - I haven't changed any SQL file.

**Comment by Helias** [comment]
we need to update this module with the new table structure of creature_template

**Comment by locus313** [comment]
@UltraNix I updated the sql, can you update your pr?

**Comment by ghost** [comment]
@locus313 Done.

**Review by Helias — APPROVED** [review]

**Comment by locus313** [comment]
Thanks @UltraNix !

**Pull request merged**
